const categoriesData = [
    {
        "title": "Agentes biológicos, químicos y físicos",
        "id": "agentes",
        "subcategories": [
            { "name": "Agentes biológicos & materiales", "example": "Mal manejo de residuos biológicos, no esterilizar los residuos antes de disponerlos, mezcla de residuos biológicos, etc.", "nonexample": "Un derrame de cloro en el área de producción. Esto corresponde a la categoría de Agentes químicos." },
            { "name": "Agentes químicos", "example": "Mal manejo de sustancias químicas, no contar con HDS de sustancias químicas, no contar con charolas de contención de derrames, no contar con etiquetas de riesgos, trabajo en campanas de extracción con el medidor de flujo en amarillo y/o rojo.", "nonexample": "Mezclar basura común con residuos de jeringas usadas. Esto corresponde a la categoría de Agentes biológicos & materiales." },
            { "name": "Registros químicos & restricción", "example": "No contar con un inventario de sustancias y no tener identificadas las sustancias con restricción p.e. cancerigenos.", "nonexample": "No etiquetar un tablero eléctrico con el nivel de voltaje. Esto corresponde a la categoría de Comunicación de peligros." },
            { "name": "Ruido", "example": "Personal con exposición a ruido constante mayor a 85 dB, área no señalizada con exposición a ruido mayor a 85 dB.", "nonexample": "Conversaciones en voz alta en el área de oficinas. Esto corresponde a la categoría de Bienestar de los empleados." },
            { "name": "Sustancias controladas", "example": "Mal manejo de sustancias químicas, no contar con HDS de sustancias químicas, no contar con etiquetas de riesgos, etc.", "nonexample": "Almacenar cajas de papelería obstruyendo un pasillo. Esto corresponde a la categoría de Limpieza / orden o Resbalones y caídas." },
            { "name": "Comunicación de peligros", "example": "Colocación de etiquetas de riesgos por ejemplo eléctricos, partes en movimiento, superficies calientes, ruido, etc.", "nonexample": "Falta de un procedimiento escrito para el manejo de químicos. Esto corresponde a la categoría de Documentación." },
            { "name": "Higiene industrial", "example": "Personal Ocupacionalmente Expuesto (POE) sin vigilancia médica.", "nonexample": "Un empleado con gripe trabajando en la oficina. Esto corresponde a la categoría de Salud ocupacional." },
            { "name": "Transporte: mercancias peligrosas", "example": "Recepción de cilindros de gas en posición horizontal, recepción de materias primas y sustancias derramadas.", "nonexample": "Un camión de reparto de comida estacionado en zona prohibida. Esto corresponde a la categoría de Vehículos." },
            { "name": "Seguridad radiológica", "example": "Introducir fuentes de radiación sin autorización.", "nonexample": "Usar el horno de microondas del comedor con la puerta en mal estado. Esto corresponde a la categoría de Deficiencia en las instalaciones." },
            { "name": "Restricción de sustancias peligrosas", "example": "Introducir sustacias peligrosas sin autorización de EH&S (esta prohibido el asbesto, mercurio, cadmio).", "nonexample": "Comprar un nuevo tipo de aceite lubricante para una máquina sin evaluación. Esto corresponde a la categoría de Compras." },
            { "name": "Almacenamiento", "example": "Almacenar sustancias químicas incompatibles en la misma charola de contención, no contar con charolas de contención.", "nonexample": "Guardar herramientas en el casillero personal en lugar del gabinete asignado. Esto corresponde a la categoría de Procedimientos de operación." },
            { "name": "Pesticidas", "example": "Introducir nuevos pesticidas sin contar con autorización de EH&S.", "nonexample": "Utilizar un aromatizante ambiental no autorizado en la oficina. Esto corresponde a la categoría de Compras." }
        ]
    },
    {
        "title": "Medioambiente",
        "id": "medioambiente",
        "subcategories": [
            { "name": "Aire", "example": "No contar con reporte de emisión de colectores y calderas.", "nonexample": "Malos olores provenientes de comida en el refrigerador del comedor. Esto corresponde a la categoría de Limpieza / orden." },
            { "name": "Energia", "example": "Dejar áreas con luces prendidas y equipos prendidos.", "nonexample": "El consumo de combustible de un montacargas de gas operando en el almacén. Esto corresponde a la categoría de Vehiculos industriales motorizados." },
            { "name": "Responsabilidad extendida del proveedor", "example": "No contratar proveedores de equipos o servicios responsables con el medioambiente.", "nonexample": "Un contratista trabajando sin su equipo de protección personal. Esto corresponde a la categoría de Gestión de contratistas." },
            { "name": "Agua: aguas residuales", "example": "Tirar sustancias químicas peligrosas al drenaje.", "nonexample": "Una fuga en la tubería de agua potable del baño. Esto corresponde a la categoría de Agua." },
            { "name": "Ruido (medioambiente)", "example": "Comprar equipos que generen ruido mayor a 85 dB.", "nonexample": "El sonido de la alarma de incendios durante un simulacro. Esto corresponde a la categoría de Preparación y respuesta a emergencias." },
            { "name": "Abastecimiento responsable", "example": "No contratar proveedores de materias primas responsables con el medioambiente.", "nonexample": "Recibir un lote de materia prima con el empaque dañado. Esto corresponde a la categoría de Proveedor." },
            { "name": "Agua: agua potable", "example": "Agua potable sin certificado de calidad.", "nonexample": "Piso mojado cerca de un bebedero por salpicaduras. Esto corresponde a la categoría de Resbalones y caídas." },
            { "name": "Agua", "example": "Dejar llaves o tomas de agua abiertas, fuaas de agua, etc.", "nonexample": "Un derrame de refresco en el área de descanso. Esto corresponde a la categoría de Resbalones y caídas." },
            { "name": "Diseño sustentable y etiquetado", "example": "Adquirir material de empaque que genere impacto ambiental, por ejemplo adquirir matriales no reciclables.", "nonexample": "Etiquetas de riesgo de productos químicos borrosas o ilegibles. Esto corresponde a la categoría de Comunicación de peligros." },
            { "name": "Residuos", "example": "Mal manejo de residuos, contenedores no etiquetados.", "nonexample": "Acumulación de polvo en las estanterías del almacén. Esto corresponde a la categoría de Limpieza / orden." },
            { "name": "Suelo", "example": "Derrames de sustancias al suelo, reporte e investigación.", "nonexample": "Piso resbaloso por cera recién aplicada sin señalización. Esto corresponde a la categoría de Resbalones y caídas." },
            { "name": "Agua: Agua pluvial", "example": "Contaminación de drenaje pluvial.", "nonexample": "Charcos de agua dentro de la nave por una gotera en el techo. Esto corresponde a la categoría de Deficiencia en las instalaciones." }
        ]
    },
    {
        "title": "Ergonomía",
        "id": "ergonomia",
        "subcategories": [
            { "name": "Estación de trabajo de la computadora", "example": "Silla de escritorio no ergonomica o en mal estado, puesto de trabajo en oficinas no adecuado, etc.", "nonexample": "Levantar una caja pesada de papel para la impresora de forma incorrecta. Esto corresponde a la categoría de Lavantamiento." },
            { "name": "Lavantamiento", "example": "Levantamiento de cargas mayores a 20 Kg por parte de mujeres y mayores a 25 Kg por parte de hombres.", "nonexample": "Tropezar al caminar mientras se carga una caja. Esto corresponde a la categoría de Resbalones y caídas." },
            { "name": "Empujar/Tirar", "example": "Empujar o jalar cargas sin las condiciones ergonomicas apropiadas.", "nonexample": "Alcanzar un objeto en una repisa muy alta estirando excesivamente el brazo. Esto corresponde a la categoría de Sobreesfuerzo." },
            { "name": "Trnstorno de trauma acumulativo / movimiento repetitivo", "example": "Movimientos repetitivos en las actividades desempañadas por el personal.", "nonexample": "Tropezar con un cable suelto en el suelo de la oficina. Esto corresponde a la categoría de Resbalones y caídas." },
            { "name": "Sobreesfuerzo", "example": "Sobreesferzo para la ejecuión de actividades relacionadas al trabajo.", "nonexample": "Caminar una larga distancia desde el estacionamiento hasta la entrada. Esto corresponde a la categoría de Seguridad del peatón." }
        ]
    },
    {
        "title": "Seguridad Ocupacional",
        "id": "seguridad",
        "subcategories": [
            { "name": "Manejo de animales", "example": "No respetar la fauna del sitio.", "nonexample": "Presencia de insectos o roedores en el área de comedor. Esto corresponde a la categoría de Control de plagas." },
            { "name": "Caldera / Recipiente sujeto a presión", "example": "No contar con los dictamanes emitidos por la STPS, no contar con la indentificación del recipiente sujeto a presión, etc.", "nonexample": "Un extintor de incendios con la carga vencida. Esto corresponde a la categoría de Seguridad contra incendios." },
            { "name": "Espacio confinado", "example": "Entrada a espacios confinados sin un permiso de trabajo autorizado, no contar con el EPP apropiado para espacios confinados, no estar capacitado para ingreso.", "nonexample": "Trabajar en una postura incómoda debajo de un escritorio. Esto corresponde a la categoría de Ergonomía." },
            { "name": "Levantamiento de cargas críticas", "example": "Levantamiento de cargas críticas sin permiso de trabajo, personal no capacitado para el trabajo.", "nonexample": "Levantar manualmente un garrafón de agua para el dispensador. Esto corresponde a la categoría de Lavantamiento (Ergonomía)." },
            { "name": "Seguridad eléctrica", "example": "Tableros eléctricos abiertos, multicontactos, cables en mal estado, instalaciones sin conexión a tierra.", "nonexample": "Dejar la luz de la oficina encendida durante la noche. Esto corresponde a la categoría de Energía." },
            { "name": "Elevador", "example": "Equipos de elevación (polipasto) sin calibración.", "nonexample": "Un montacargas bloqueando el acceso al elevador de personal. Esto corresponde a la categoría de Seguridad en almacén." },
            { "name": "Excavación", "example": "Excavaciones sin permiso de trabajo autorizado (excavaciones a partir de 30 cm de profundidad requieren permiso).", "nonexample": "Un bache profundo en el asfalto del estacionamiento. Esto corresponde a la categoría de Deficiencia en las instalaciones." },
            { "name": "Seguridad de explosión", "example": "Equipos sin aterrizaje a tierra, falta de equipos contra incendio.", "nonexample": "El ruido fuerte y repentino de una máquina al fallar. Esto corresponde a la categoría de Falla mecánica o del sistema." },
            { "name": "PSM tier 1/tier 2", "example": "Ingreso de equipos no ATEX a cuartos PSM (granulaciones y mezclado de polvos).", "nonexample": "Usar solventes de limpieza comunes sin guantes. Esto corresponde a la categoría de Equipo de protección personal." },
            { "name": "Seguridad contra incendios", "example": "Equipos contra incendios sin inspección (hidrantes, red contra indendios, extintores) o falta de alguno en áreas críticas.", "nonexample": "Falta de señalización de rutas de evacuación. Esto corresponde a la categoría de Comunicación." },
            { "name": "Trabajo en caliente", "example": "Trabajo de corte y soldadura sin un permiso de trabajo autorizado, personal sin capacitación y EPP adecuado.", "nonexample": "Calentar comida que genera mucho humo en el microondas. Esto corresponde a la categoría de Comida." },
            { "name": "Bloqueo - Etiquetado (LOTO)", "example": "Trabajo de LOTO sin un permiso de trabajo autorizado o sin un procedimiento establecido, personal sin capacitación.", "nonexample": "Apagar una computadora al final del día. Esto es un procedimiento operativo normal, no un riesgo." },
            { "name": "Ruptura de tubería", "example": "Trabajo de ruptura de tubería que conducen fluidos peligrosos sin permiso de trabajo autorizado.", "nonexample": "Una fuga en una manguera de jardín. Esto corresponde a la categoría de Agua." },
            { "name": "Seguridad de maquinaria", "example": "Guardas en mal estado, dispositivos de seguridad de maquinaria sin correcto funcionamiento, potenciales puntos de atrapamiento sin medidas de seguridad.", "nonexample": "Una impresora de oficina atascada. Esto corresponde a la categoría de Mantenimiento." },
            { "name": "Seguridad en oficina", "example": "Condiciones inseguras en las instalaciones de las oficinas de personal administrativo.", "nonexample": "Un conflicto verbal entre dos compañeros de trabajo. Esto corresponde a la categoría de Factores humanos." },
            { "name": "Seguridad del peaton", "example": "No respetar los pasillos asignados para transito de peatones en exteriores y estacionamiento.", "nonexample": "Un empleado corriendo por los pasillos. Esto corresponde a la categoría de Factores humanos." },
            { "name": "Vehiculos industriales motorizados", "example": "Ir a más de 10 Km/h, montacargas sin mantenimiento, personal no capacitado para uso de montacargas.", "nonexample": "Un visitante estaciona su auto bloqueando una salida de emergencia. Esto corresponde a la categoría de Preparación y respuesta a emergencias." },
            { "name": "Transporte: seguridad de la carga", "example": "Transportes con puertas abiertas de la caja.", "nonexample": "Un camión de reparto excediendo el límite de velocidad fuera del sitio. Esto corresponde a la categoría de Vehículos." },
            { "name": "Bypass seguro", "example": "Bypass en dispositivos de seguridad y sin permiso autorizado.", "nonexample": "Tomar un atajo por el césped en lugar de usar la banqueta. Esto corresponde a la categoría de Seguridad del peatón." },
            { "name": "Resbalones y caídas", "example": "Caminar mientras se usa el celular, bordes que pudieran provocar una caída, derrames de liquidos o alimentos que pudieran provocar una caída, pisos mojados sin señaletica.", "nonexample": "Caída de una caja desde un estante alto. Esto corresponde a la categoría de Caída de objetos." },
            { "name": "Fuentes de ignición no controladas", "example": "Potenciales fuentes de ignición que no tengan algún sistema contra incendio para mitigar el riesgo.", "nonexample": "Una bombilla de luz que se quema y deja de funcionar. Esto corresponde a la categoría de Mantenimiento." },
            { "name": "Vehículos", "example": "Vehículos a más de 15 Km/h, vehículos sin intermitentes, no respetar los flujos del estacionamiento.", "nonexample": "Un montacargas bloqueando un pasillo peatonal. Esto corresponde a la categoría de Vehiculos industriales motorizados." },
            { "name": "Seguridad en almacén", "example": "Racks sin inspección, no respetar los pasillos asignados para peatones, montacargas con exceso de velocidad.", "nonexample": "Un error en el conteo del inventario de productos. Esto corresponde a la categoría de Documentación." },
            { "name": "Trabajo en alturas", "example": "Trabajo sin permiso de trabajo autorizado a más de 1.8 m, no seguir las condiciones para uso de escaleras, no uso de arnes, linea de vida, personal no capacitado.", "nonexample": "Subirse a una silla de oficina para alcanzar un objeto. Esto corresponde a la categoría de Resbalones y caídas." },
            { "name": "Permiso de trabajo", "example": "Cualquier desviación a las 8 reglas salvavidas del sitio.", "nonexample": "No registrar la hora de entrada en el sistema. Esto es una falta administrativa, no un riesgo de EHS." },
            { "name": "Caida de objetos", "example": "Cualquier objeto a más de 1.5 m que pudiera caerse y que no este almacenado de forma correcta.", "nonexample": "Dejar caer un lápiz al suelo desde el escritorio. Esto no representa un riesgo reportable." },
            { "name": "Seguridad de transportistas", "example": "No respetar las reglas de seguridad del sitio por parte de personal transportista.", "nonexample": "Un conductor de transporte que no conoce la dirección de entrega. Esto corresponde a la categoría de Proveedor." }
        ]
    },
    {
        "title": "General o administración del sistema de EH&S",
        "id": "general",
        "subcategories": [
            { "name": "Auditorias e inspecciones", "example": "No dar seguimiento a observaciones de auditorias.", "nonexample": "Una revisión del desempeño laboral de un empleado. Esto corresponde a la categoría de Roles y responsabilidades (de RRHH)." },
            { "name": "Deficiencia en las instalaciones", "example": "Cualquier oportunidad en las instalaciones.", "nonexample": "La decoración de la oficina no es del agrado de un empleado. Esto corresponde a la categoría de Bienestar de los empleados." },
            { "name": "Comunicación", "example": "Comunicación de riesgos o intrucciones de seguridad (señaleticas).", "nonexample": "Un correo electrónico sobre la fiesta de fin de año. Esto es comunicación general, no un riesgo." },
            { "name": "Gestión de contratistas", "example": "No respetar las reglas de seguridad del sitio por parte de personal contratista, contratistas sin autorización de ingreso.", "nonexample": "Un proveedor que entrega la materia prima equivocada. Esto corresponde a la categoría de Proveedor." },
            { "name": "Documentación", "example": "Oportunidades en la documentación de procedimientos relacionados a seguridad.", "nonexample": "Falta de minutas en una reunión de marketing. Esto es un procedimiento operativo no relacionado a EHS." },
            { "name": "Gestión de cambios de seguridad", "example": "No realizar MOC para ejecución de cambios que impactan a seguridad o no alinearse a las acciones establecidas.", "nonexample": "Cambiar el color de la pintura de las paredes de la oficina. Esto corresponde a Gestión del cambio (no de seguridad)." },
            { "name": "Preparación y respuesta a emergencias", "example": "Equipos de emergergecia sin inspección, bloqueo de puertas y rutas de evacuación, falta de conocimiento de los protocolos.", "nonexample": "No tener suficientes snacks en la máquina expendedora. Esto corresponde a la categoría de Comida." },
            { "name": "Procedimientos de operación", "example": "Procedimientos de operación no alineados con ART o procedimientos de seguridad.", "nonexample": "Un empleado que no sigue el código de vestimenta. Esto corresponde a la categoría de Factores humanos." },
            { "name": "Competencia", "example": "Falta de conocimientos o habilidades del personal que realiza un trabajo.", "nonexample": "Un empleado que no sabe usar un nuevo software de contabilidad. Esto corresponde a Entrenamiento (no de seguridad)." },
            { "name": "Mantenimiento", "example": "Falta de mantenimiento a equipos como montacargas, patines, equipos de manufactura o laboratorio.", "nonexample": "La planta de ornato de la recepción necesita agua. Esto corresponde a la categoría de Limpieza / orden." },
            { "name": "Comida", "example": "Comida en mal estado (proveida por comedor), sintomas de intoxicación por comida proveida del comedor.", "nonexample": "A un empleado no le gustó el menú del día en el comedor. Esto corresponde a la categoría de Bienestar de los empleados." },
            { "name": "Evaluación de peligros y riesgos", "example": "Falta de ART para una actividad, falta de actualización de los ART, ART no alineados al trabajo real, ART no firmado por el personal, ART sin medidas de contención de riesgos adecuadas.", "nonexample": "No prever que un proyecto tomaría más tiempo del estimado. Esto corresponde a la gestión de proyectos, no a un riesgo de EHS." },
            { "name": "Factores humanos", "example": "Capacitación deficiente o falta de la misma, administración deficiente, procedimientos poco claros.", "nonexample": "Un empleado se siente cansado un lunes por la mañana. Esto corresponde a la categoría de Bienestar de los empleados." },
            { "name": "Gestión del cambio", "example": "Falta de gestión en las actividades a realizar previo a llevar a cabo un cambio que impacta a seguridad.", "nonexample": "Implementar un nuevo sistema de software para recursos humanos. Esto no es un cambio que impacte a seguridad." },
            { "name": "Falla mécanica o del sistema", "example": "Falla en la mécanica o sistema de un equipo de operaciones o de laboratorio que provoca una condición insegura.", "nonexample": "La red de internet de la empresa está lenta. Esto corresponde a una Deficiencia en las instalaciones (de TI)." },
            { "name": "Trabajo no rutinario", "example": "Trabajo realizado una vez al año sin los controles de seguridad establecidos.", "nonexample": "Hacer horas extras para terminar un reporte urgente. Esto corresponde a Roles y responsabilidades." },
            { "name": "Salud ocupacional", "example": "Falta de vigilancias médicas al personal ocupacionalmente expuesto.", "nonexample": "Otorgar un día libre a un empleado por su cumpleaños. Esto corresponde a la categoría de Bienestar de los empleados." },
            { "name": "Imanes", "example": "Equipos con imanes que tengan el potencial de causar daño al personal.", "nonexample": "Usar imanes decorativos en el refrigerador del comedor. Esto no representa un riesgo reportable." },
            { "name": "Procedimientos", "example": "Procedimientos de seguridad poco claros o confusos.", "nonexample": "Instrucciones poco claras para armar un mueble de oficina. Esto corresponde a la categoría de Documentación (del proveedor)." },
            { "name": "Otros (especificar)", "example": "Cualquier otra categoria no enlistada.", "nonexample": "Un riesgo que ya está claramente definido en otra categoría." },
            { "name": "Equipo de protección personal", "example": "Personal que no usa EPP acorde al tipo de actividades (operaciones, laboratorio, almacén, trabajos peligrosos).", "nonexample": "Un empleado que olvida su gafete de identificación. Esto es un riesgo de seguridad patrimonial, no personal." },
            { "name": "Compras", "example": "Compra de equipos o maquinaria no evaluada y autorizada por EH&S.", "nonexample": "Comprar una marca de café diferente para la sala de descanso. Esto corresponde a la categoría de Bienestar de los empleados." },
            { "name": "Cumplimiento regulatorio / permisos regulatorios", "example": "Falta de permisos regulatorios tales como Programa Interno de Protección Civil, dictamenes de recipientes sujetos a presión, dictamén eléctrico, etc.", "nonexample": "No tener permiso del supervisor para salir temprano. Esto es un procedimiento operativo interno." },
            { "name": "Roles y responsabildades", "example": "Falta de claridad en los roles y responsabilidades de equipos de trabajo como brigada, CSH, etc.", "nonexample": "Incertidumbre sobre quién debe organizar la fiesta de navidad. Esto corresponde a la categoría de Factores humanos." },
            { "name": "Sistema de tanques", "example": "Tanques sin protección contra derrames.", "nonexample": "El tanque de gasolina del auto de un empleado está casi vacío. Esto corresponde a Vehículos (y no es un riesgo del sitio)." },
            { "name": "Entrenamiento", "example": "Falta de entrenamiento a personal que ejecuta una actividad o que viola alguna regla de seguridad.", "nonexample": "Falta de capacitación en liderazgo para un gerente. Esto corresponde a Competencia (no de seguridad)." },
            { "name": "Bienestar de los empleados", "example": "Factores de riesgo psicosocial.", "nonexample": "Desacuerdo sobre la temperatura del aire acondicionado. Esto corresponde a la categoría de Factores humanos." },
            { "name": "Permisos de trabajo", "example": "Cualquier desviación a las 8 reglas salvavidas del sitio enfocadas a permisos de trabajo peligrosos.", "nonexample": "Solicitar un permiso de ausencia por vacaciones. Esto es un procedimiento de RRHH." },
            { "name": "Gestión de CAPA", "example": "CAPA de seguridad no efectivas.", "nonexample": "Un plan de acción para mejorar las ventas. Esto es una CAPA de negocio, no de seguridad." }
        ]
    },
    {
        "title": "Administación de las instalaciones",
        "id": "instalaciones",
        "subcategories": [
            { "name": "Condición ambiental / monitoreo", "example": "No tener estudios de monitoreo ambiental (ruido e iluminación).", "nonexample": "El pronóstico del tiempo indica que lloverá mañana. Esto es información general, no un monitoreo del sitio." },
            { "name": "Calificación / validación", "example": "Falta de calificación a un proceso o equipo.", "nonexample": "Verificar las referencias laborales de un nuevo candidato. Esto corresponde a un procedimiento de RRHH." },
            { "name": "Proveedor", "example": "Proveedores de bienes o servicios no autorizados por EH&S.", "nonexample": "Un cliente que se queja de la calidad de un producto. Esto es una cuestión de calidad, no un riesgo de proveedor." },
            { "name": "Control de plagas", "example": "Plagas de animales, vegetación, etc.", "nonexample": "La mascota de un empleado esperando en el auto. Esto corresponde a Manejo de animales (y no es una plaga)." },
            { "name": "Calibración", "example": "Falta de calibración a equipos criticos de seguridad.", "nonexample": "Ajustar el brillo y contraste del monitor de una computadora. Esto corresponde a Ergonomía." },
            { "name": "Limpieza / orden", "example": "Falta de orden y limpieza en las áreas de trabajo.", "nonexample": "Un escritorio personal desordenado con papeles y tazas. Esto es una preferencia personal y no un riesgo colectivo, a menos que obstruya pasillos." }
        ]
    }
];
